include:
  - lib/common/.gitlab-ci.yml
  - services/admin/.gitlab-ci.yml
  - services/core/.gitlab-ci.yml
  - services/identity/.gitlab-ci.yml
  - services/authentication/.gitlab-ci.yml
  - services/reservation/.gitlab-ci.yml