image: adoptopenjdk/openjdk14:jdk-14.0.2_12

stages:
  - build
  - validate
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

service-admin-build:
  stage: build
  script:
    ./gradlew --build-cache :services:admin:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

service-admin-checkstyle:
  stage: validate
  script: ./gradlew :services:admin:checkstyleMain :services:admin:checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

#service-admin-pmd:
  #stage: validate
  #script: ./gradlew :services:admin:pmdMain :services:admin:pmdTest

service-admin-test:
  stage: test
  script:
    - ./gradlew :services:admin:test :services:admin:jacocoTestReport
    - cat services/admin/build/reports/jacoco/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
