image: adoptopenjdk/openjdk14:jdk-14.0.2_12

stages:
  - build
  - validate
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

service-reservation-build:
  stage: build
  script:
    ./gradlew --build-cache :services:reservation:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

service-reservation-checkstyle:
  stage: validate
  script: ./gradlew :services:reservation:checkstyleMain :services:reservation:checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

service-reservation-pmd:
  stage: validate
  script: ./gradlew :services:reservation:pmdMain :services:reservation:pmdTest

service-reservation-test:
  stage: test
  script:
    - ./gradlew :services:reservation:test :services:reservation:jacocoTestReport
    - cat services/reservation/build/reports/jacoco/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/